### ISSUE TITLE
High Loss and Unsatisfactory Output with Modified Graph Structure

### ISSUE THREAD

**Issue by yminglai** [yolandalalala/DeepGD#1]
I modified the code to use an incomplete graph instead of a completed graph, but the output doesn't look satisfying and primarily displays data from the top-left to the bottom-right. Additionally, I'm encountering a very high loss with this configuration.

Questions:
What kind of stress loss function did you use in the referenced paper?
Could you provide any suggestions or guidelines for configuring the graph structure to achieve better results?

Additional Information:
The issue was encountered after modifying the graph structure. I switch from the completed graph to the original graphs in your code when evaluating the stress loss.

The high loss issue occurs consistently.

And in the paper, it is said that you were using 400 epochs, but in the demo, it's 600. So which one is better? Additionally, would you like to suggest best hyper parameters in your code.

Please provide any insights or recommendations you may have. Thank you!

![deepgd](https://github.com/yolandalalala/DeepGD/assets/150297217/6adacd9e-a412-4755-929f-a7972bc6bc39)

**Comment by yolandalalala** [comment]
The stress function implementation we used in the paper is exactly the same as the code we provided in this repo. Also, the complete graph is required in DeepGD, as already explained in the paper.

**Comment by yminglai** [comment]
Is the evaluation based on completed graphs or graphs with original edges? Additionally, can the evaluation step be demonstrated in the demo?
