### ISSUE TITLE
Question on Training Models

### ISSUE THREAD

**Issue by yminglai** [yolandalalala/DeepGD#2]
![download_1](https://github.com/yolandalalala/DeepGD/assets/150297217/118db906-872c-483d-8081-2d59b9709598)
![download_2](https://github.com/yolandalalala/DeepGD/assets/150297217/b6bfd0bd-3fc0-4789-8a1d-917048c9914c)
![download](https://github.com/yolandalalala/DeepGD/assets/150297217/d1c5a8be-042a-43f4-a134-87ef9dc056ca)

 We trained the model and getting some strange outputs. Did you met some similar problems before? We trained on completed graph but only pick the nodes and edges back as original Rome Dataset. These graphs are not similar to the ones you mentioned in the paper. How can I fix that?

thanks

**Comment by yolandalalala** [comment]
We have updated the implementation and released the model checkpoints. Please feel free to check it out.
